export const COUNTRY_NAME_LIST = {
  TAIPEI: "Taipei City",
  NEW_TAIPEI: "New TaipeiCity",
  TAOYUAN_CITY: "Taoyuan City",
  TAICHUNG_CITY: "Taichung City",
  TAINAN_CITY: "Tainan City",
  KAOHSIUNG_CITY: "Kaohsiung City",
  YILAN_COUNTRY: "Yilan County",
  HSINCHU_COUNTRY: "Hsinchu County",
  MIAOLI_COUNTRY: "Miaoli County",
  CHANGHUA_COUNTRY: "Changhua County",
  NANTOU_COUNTRY: "Nantou County",
  YUNLIN_COUNTRY: "Yunlin County",
  CHIAYI_COUNTRY: "Chiayi County",
  PINGTUNG_COUNTRY: "Pingtung County",
  TAITUNG_COUNTRY: "Taitung County",
  HUALIEN_COUNTRY: "Hualien County",
  KEELUNG_CITY: "Keelung City",
  HSINCHU_CITY: "Hsinchu City",
  CHIAYI_CITY: "Chiayi City",
}

export const COUNTRY_ID_LIST = {
  TAIPEI: "A",
  NEW_TAIPEI: "F",
  TAOYUAN_CITY: "H",
  TAICHUNG_CITY: "B",
  TAINAN_CITY: "D",
  KAOHSIUNG_CITY: "E",
  YILAN_COUNTRY: "G",
  HSINCHU_COUNTRY: "J",
  MIAOLI_COUNTRY: "K",
  CHANGHUA_COUNTRY: "N",
  NANTOU_COUNTRY: "M",
  YUNLIN_COUNTRY: "P",
  CHIAYI_COUNTRY: "Q",
  PINGTUNG_COUNTRY: "T",
  TAITUNG_COUNTRY: "V",
  HUALIEN_COUNTRY: "U",
  KEELUNG_CITY: "C",
  HSINCHU_CITY: "O",
  CHIAYI_CITY: "I",

}

