version: "3"

services:
    web:
        image: "nginx:alpine"
        container_name: "web"
        depends_on:
            - api
        ports:
            - "80:80"
        volumes:
            - ./web/conf.d:/etc/nginx/conf.d
    api:
        image: "api"
        container_name: "api"
        links:
            - db
        ports:
            - "8765:8765"
        expose:
            - 8765
        working_dir: /api
        depends_on:
            - db
        volumes:
            - ./api:/api
        command: ["python3","/api/api.py","-p","8765"]
    db:
        image: "postgres"
        container_name: "postgres"
        ports:
            - "5432:5432"
        env_file:
            - ./env/postgres.env
        volumes:
            - ./db/dbdata:/var/lib/postgresql/data
            - ./db:/db
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
          - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
          - PGADMIN_DEFAULT_PASSWORD=pw2pgadmin
        links:
          - db
        ports:
          - "8964:80"
        depends_on:
          - db
